### ISSUE TITLE
can't install pyqt6-tools

### ISSUE THREAD

**Issue by NiiV3AU** [altendky/pyqt-tools#102]
C:\Users\->pip install pyqt6-tools
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl (29 kB)
Collecting click
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting pyqt6==6.1.0
  Using cached PyQt6-6.1.0-cp36.cp37.cp38.cp39-none-win_amd64.whl (5.3 MB)
Collecting python-dotenv
  Using cached python_dotenv-0.19.2-py2.py3-none-any.whl (17 kB)
Collecting pyqt6-plugins<6.1.0.3,>=6.1.0.2.2
  Using cached pyqt6_plugins-6.1.0.2.2-cp39-cp39-win_amd64.whl (74 kB)
Requirement already satisfied: PyQt6-sip<14,>=13.1 in c:\users\-\appdata\local\programs\python\python39\lib\site-packages (from pyqt6==6.1.0->pyqt6-tools) (13.2.0)
Requirement already satisfied: PyQt6-Qt6>=6.1.0 in c:\users\-\appdata\local\programs\python\python39\lib\site-packages (from pyqt6==6.1.0->pyqt6-tools) (6.2.2)
Collecting qt6-tools<6.1.0.2,>=6.1.0.1.2
  Using cached qt6_tools-6.1.0.1.2-py3-none-any.whl (13 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting qt6-applications<6.1.0.3,>=6.1.0.2.2
  Using cached qt6_applications-6.1.0.2.2-py3-none-win_amd64.whl (60.4 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\cli\base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\commands\install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError

**Comment by tonal** [comment]
For clean Python 3.10.5 virtualenv:
```
$ pip install pyqt6-tools
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl (29 kB)
Requirement already satisfied: click in /home/tonal/.pyenv/versions/3.10.5/envs/epool-qt7tool/lib/python3.10/site-packages (from pyqt6-tools) (8.1.3)
Collecting pyqt6==6.1.0
  Downloading PyQt6-6.1.0-cp36.cp37.cp38.cp39-abi3-manylinux_2_28_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 6.8 MB/s eta 0:00:00
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.0.3.3.2-py3-none-any.whl (29 kB)
  Using cached pyqt6_tools-6.0.2.3.2-py3-none-any.whl (29 kB)
Collecting pyqt6==6.0.2
  Using cached PyQt6-6.0.2-cp36.cp37.cp38.cp39-abi3-manylinux_2_28_x86_64.whl (6.7 MB)
Collecting python-dotenv
  Using cached python_dotenv-0.20.0-py3-none-any.whl (17 kB)
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.0.1.3.2-py3-none-any.whl (29 kB)
ERROR: Cannot install pyqt6-tools==6.0.1.3.2, pyqt6-tools==6.0.2.3.2, pyqt6-tools==6.0.3.3.2 and pyqt6-tools==6.1.0.3.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    pyqt6-tools 6.1.0.3.2 depends on pyqt6-plugins<6.1.0.3 and >=6.1.0.2.2
    pyqt6-tools 6.0.3.3.2 depends on pyqt6-plugins<6.0.3.3 and >=6.0.3.2.2
    pyqt6-tools 6.0.2.3.2 depends on pyqt6-plugins<6.0.2.3 and >=6.0.2.2.2
    pyqt6-tools 6.0.1.3.2 depends on pyqt6-plugins<6.0.1.3 and >=6.0.1.2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by Saphyel** [comment]
This is still happening... Any fix for this?

**Comment by altendky** [comment]
Hey all, this is a common note I'm adding to several issues.

I apologize for the hassle you have all dealt with around this project.  I don't work with Qt anymore and every time I've come back to this I have run into various problems trying to get it going again.  This time I made it through the five days of work to get the release out (fingers crossed that it actually works).  It would be great to get some community involvement around updating and debugging whatever issues come up.  Maybe the next Python, Qt, or PyQt release will provide an opportunity for someone to offer that.  Maybe I'll find time to continue cleaning this up so it's a bit more maintainable.  If interested, there's been some discussion about the project at https://github.com/altendky/pyqt-tools/issues/110.

In an effort to make it easier to monitor issues around the latest release I am closing this issue.  Discussion can continue if still applicable, but I want to make it easier to move forward.  If there are issues with the new releases, please open new issues.

Things to be aware of that may ease some cases:
- If you just want the Qt applications, you can directly use `qt-tools` which provides helpers around `qt-applications`.  This skips the PyQt specific layers.  You won't have access to the plugins, such as for showing custom PyQt Designer widget plugins in Designer, but you also won't have the hassle of needing a version matching your PyQt version.  At least not quite as closely.
- If I once again fail to maintain this, or you just want a specific version I didn't include, you can set environment variables to select the versions when building.  `PYQT_VERSION=6.5.0 QT_VERSION=6.5.2 venv/bin/pip install git+https://github.com/altendky/qt-applications@v2.3` for example would try to build and install qt-applications v2.3 including (a theoretical future) PyQt version 6.5.0 and Qt 6.5.2.  I'm sure there are corners around this, but it would be relevant.
