### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by liudonghua123** [altendky/pyqt-tools#108]
I update my python to 3.11 recently, now I try to install `pyqt5` and `pyqt5-tools`. The `pyqt5` installation is success, but `pyqt5-tools` is failed with the the similar errors when I install on python 3.10.

So I tried the same workaround I commented on https://github.com/altendky/pyqt-tools/issues/98#issuecomment-1058910482 which I used on python 3.10. 

```shell
wget https://files.pythonhosted.org/packages/5e/1b/5edc9b05c33d75f9cea3159ae3d1ff11369a0afe84eddaf5b3974b0769d1/pyqt5_plugins-5.15.4.2.2-cp39-cp39-win_amd64.whl
mv pyqt5_plugins-5.15.4.2.2-cp39-cp39-win_amd64.whl pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl
pip install pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl
```

But it failed with the following errors.

<details>
<summary>pip install D:\Downloads\pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl</summary>

```
C:\Users\Liu.D.H>python -V
Python 3.11.0

C:\Users\Liu.D.H>pip -V
pip 22.3.1 from C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)

C:\Users\Liu.D.H>
C:\Users\Liu.D.H>pip install pyqt5
Requirement already satisfied: pyqt5 in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (5.15.7)
Requirement already satisfied: PyQt5-sip<13,>=12.11 in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (from pyqt5) (12.11.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.0 in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (from pyqt5) (5.15.2)

C:\Users\Liu.D.H>
C:\Users\Liu.D.H>pip install D:\Downloads\pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl
Processing d:\downloads\pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl
Requirement already satisfied: click in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (from pyqt5-plugins==5.15.4.2.2) (8.1.3)
Collecting pyqt5==5.15.4
  Using cached PyQt5-5.15.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-118b00b5\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-118b00b5\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-118b00b5\overlay\Lib\site-packages\sipbuild\project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-install-af21yb96\pyqt5_95b94776b0bf4a33ab12b7eb411b877f\project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-118b00b5\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-118b00b5\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-118b00b5\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\Liu.D.H>
```
</details>

I have to overwrite `Requires-Dist: pyqt5` section from `Requires-Dist: pyqt5 (==5.15.4)` to `Requires-Dist: pyqt5` in **pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl/pyqt5_plugins-5.15.4.2.2.dist-info/METADATA**.

Then install again, I can install `pyqt5-tools` successfully now.

<details>
<summary>pip install D:\Downloads\pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl</summary>

```
C:\Users\Liu.D.H>pip install D:\Downloads\pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl
Processing d:\downloads\pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.whl
Requirement already satisfied: click in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (from pyqt5-plugins==5.15.4.2.2) (8.1.3)
Requirement already satisfied: pyqt5 in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (from pyqt5-plugins==5.15.4.2.2) (5.15.7)
Collecting qt5-tools<5.15.2.2,>=5.15.2.1.2
  Downloading qt5_tools-5.15.2.1.2-py3-none-any.whl (13 kB)
Collecting qt5-applications<5.15.2.3,>=5.15.2.2.2
  Downloading qt5_applications-5.15.2.2.2-py3-none-win_amd64.whl (60.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 MB 8.8 MB/s eta 0:00:00
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: PyQt5-sip<13,>=12.11 in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (from pyqt5->pyqt5-plugins==5.15.4.2.2) (12.11.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.0 in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (from pyqt5->pyqt5-plugins==5.15.4.2.2) (5.15.2)
Installing collected packages: qt5-applications, click, qt5-tools, pyqt5-plugins
  Attempting uninstall: click
    Found existing installation: click 8.1.3
    Uninstalling click-8.1.3:
      Successfully uninstalled click-8.1.3
Successfully installed click-7.1.2 pyqt5-plugins-5.15.4.2.2 qt5-applications-5.15.2.2.2 qt5-tools-5.15.2.1.2

C:\Users\Liu.D.H>qt5-tools
Usage: qt5-tools [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  assistant
  canbusutil
  designer
  lconvert
  licheck64
  linguist
  lprodump
  lrelease
  lrelease-pro
  lupdate
  lupdate-pro
  moc
  pixeltool
  qcollectiongenerator
  qdbus
  qdbuscpp2xml
  qdbusviewer
  qdbusxml2cpp
  qdistancefieldgenerator
  qdoc
  qgltf
  qhelpgenerator
  qlalr
  qmake
  qml
  qmlcachegen
  qmleasing
  qmlformat
  qmlimportscanner
  qmllint
  qmlmin
  qmlplugindump
  qmlpreview
  qmlprofiler
  qmlscene
  qmltestrunner
  qmltyperegistrar
  qscxmlc
  qtattributionsscanner
  qtdiag
  qtpaths
  qtplugininfo
  qtwaylandscanner
  qvkgen
  rcc
  repc
  sdpscanner
  tracegen
  uic
  xmlpatterns
  xmlpatternsvalidator

C:\Users\Liu.D.H>qt5-tools designer

C:\Users\Liu.D.H>
```
</details>

[pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.zip](https://github.com/altendky/pyqt-tools/files/10099667/pyqt5_plugins-5.15.4.2.2-py3-none-win_amd64.zip)

**Comment by randytbushman** [comment]
Same issue here!

**Comment by daniel9184** [comment]
> Thanks a lot! After changing the "Requires-Dist: pyqt6 (==6.1.0)" to "Requires-Dist: pyqt6" only on the metadata, it worked for pyqt6 on python 3.11!

**Comment by Baboomba** [comment]
Thank you, it works well!

I regret that current developer doesn't use this library. It doesn't make update properly.

**Comment by altendky** [comment]
I'm trying to make it to a new release.  https://github.com/altendky/pyqt-tools/issues/110

But yes, libraries maintained by people that don't use them aren't great.  At least not when they tend to hit all sorts of goofy corner cases when new versions of three major dependencies come out.  (Python, PyQt, and Qt)  Having other people step up and add CI coverage for new dependency releases and then debug and fix them would be a great help.

Anyways, sorry for the hassle all.  Hopefully this time I actually manage to get all the way to a release.

Also, if you don't need the plugins and just want the qt applications, consider the `qt5-tools` and `qt6-tools` packages that aren't dependent on PyQt and are also not specific to any Python 3 version.

**Comment by altendky** [comment]
Though yes, even those are behind and not providing the latest Qt application versions.

**Comment by altendky** [comment]
Hey all, this is a common note I'm adding to several issues.

I apologize for the hassle you have all dealt with around this project.  I don't work with Qt anymore and every time I've come back to this I have run into various problems trying to get it going again.  This time I made it through the five days of work to get the release out (fingers crossed that it actually works).  It would be great to get some community involvement around updating and debugging whatever issues come up.  Maybe the next Python, Qt, or PyQt release will provide an opportunity for someone to offer that.  Maybe I'll find time to continue cleaning this up so it's a bit more maintainable.  If interested, there's been some discussion about the project at https://github.com/altendky/pyqt-tools/issues/110.

In an effort to make it easier to monitor issues around the latest release I am closing this issue.  Discussion can continue if still applicable, but I want to make it easier to move forward.  If there are issues with the new releases, please open new issues.

Things to be aware of that may ease some cases:
- If you just want the Qt applications, you can directly use `qt-tools` which provides helpers around `qt-applications`.  This skips the PyQt specific layers.  You won't have access to the plugins, such as for showing custom PyQt Designer widget plugins in Designer, but you also won't have the hassle of needing a version matching your PyQt version.  At least not quite as closely.
- If I once again fail to maintain this, or you just want a specific version I didn't include, you can set environment variables to select the versions when building.  `PYQT_VERSION=6.5.0 QT_VERSION=6.5.2 venv/bin/pip install git+https://github.com/altendky/qt-applications@v2.3` for example would try to build and install qt-applications v2.3 including (a theoretical future) PyQt version 6.5.0 and Qt 6.5.2.  I'm sure there are corners around this, but it would be relevant.
