### ISSUE TITLE
ERROR: Cannot install pyqt6-tools==6.0.1.3.2, pyqt6-tools==6.0.2.3.2, pyqt6-tools==6.0.3.3.2 and pyqt6-tools==6.1.0.3.2 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by z3n-k3rn3l** [altendky/pyqt-tools#109]
While trying to install pyqt6-tools getting below error

ERROR: Cannot install pyqt6-tools==6.0.1.3.2, pyqt6-tools==6.0.2.3.2, pyqt6-tools==6.0.3.3.2 and pyqt6-tools==6.1.0.3.2 because these package versions have conflicting dependencies.
The conflict is caused by:
    pyqt6-tools 6.1.0.3.2 depends on pyqt6-plugins<6.1.0.3 and >=6.1.0.2.2
    pyqt6-tools 6.0.3.3.2 depends on pyqt6-plugins<6.0.3.3 and >=6.0.3.2.2
    pyqt6-tools 6.0.2.3.2 depends on pyqt6-plugins<6.0.2.3 and >=6.0.2.2.2
    pyqt6-tools 6.0.1.3.2 depends on pyqt6-plugins<6.0.1.3 and >=6.0.1.2.2

**Comment by BlueBeret** [comment]
have you found any solution to this issue?

**Comment by dabucejo** [comment]
I ran into this issue as well using my Mac. I looked around on the net and tried a way to get around this plugin version issue and that was to reinstall Python 3.9; I had Python 3.10 installed when I ran into this specific issue. I reinstalled to the 3.9.13 version this morning, and then I executed the "pip install pyqt6-tools" on command line, and the installation without errors. 

For references, I downloaded the package installer for 3.9 here:
https://www.python.org/downloads/macos/

Others on one of the external forums have mentioned that there are ways to try and keep 3.10 and higher but it seemed to require uninstalling and installing various components.

For references, here is where I found some of the information about reverting to Python 3.9:
https://stackoverflow.com/questions/69870103/how-to-fix-pyqt6-tools-installation-error

**Comment by altendky** [comment]
Hey all, this is a common note I'm adding to several issues.

I apologize for the hassle you have all dealt with around this project.  I don't work with Qt anymore and every time I've come back to this I have run into various problems trying to get it going again.  This time I made it through the five days of work to get the release out (fingers crossed that it actually works).  It would be great to get some community involvement around updating and debugging whatever issues come up.  Maybe the next Python, Qt, or PyQt release will provide an opportunity for someone to offer that.  Maybe I'll find time to continue cleaning this up so it's a bit more maintainable.  If interested, there's been some discussion about the project at https://github.com/altendky/pyqt-tools/issues/110.

In an effort to make it easier to monitor issues around the latest release I am closing this issue.  Discussion can continue if still applicable, but I want to make it easier to move forward.  If there are issues with the new releases, please open new issues.

Things to be aware of that may ease some cases:
- If you just want the Qt applications, you can directly use `qt-tools` which provides helpers around `qt-applications`.  This skips the PyQt specific layers.  You won't have access to the plugins, such as for showing custom PyQt Designer widget plugins in Designer, but you also won't have the hassle of needing a version matching your PyQt version.  At least not quite as closely.
- If I once again fail to maintain this, or you just want a specific version I didn't include, you can set environment variables to select the versions when building.  `PYQT_VERSION=6.5.0 QT_VERSION=6.5.2 venv/bin/pip install git+https://github.com/altendky/qt-applications@v2.3` for example would try to build and install qt-applications v2.3 including (a theoretical future) PyQt version 6.5.0 and Qt 6.5.2.  I'm sure there are corners around this, but it would be relevant.
