### ISSUE TITLE
"Code generation failed" (Launched via Python Scripts folder)

### ISSUE THREAD

**Issue by BanditFly** [altendky/pyqt-tools#34]
- Base setup info (Windows 10 - Pro):
- Installed pyqt5 and pyqt5-tools via pip3 command - No errors/installed properly/
- PATH is setup properly for Python 3.7.4 and PyQt5 and PyQt5-Tools
- Actual link to PyQt5 Designer script is:  C:\Python\Python37\Scripts\pyqt5designer.exe
=============
Steps to reproduce
=============
1) Open PyQt5 Designer (via Python Script folder)
2) Create a 1 button form and save.
3) Go to "Form>>View Code" and the error listed below is shown.
--- --- --- --- --- --- ---
Code Generation Failed
--- --- --- --- --- --- ---
Unable to launch c:/python/python37/lib/site-packages/pyqt5_tools/Qt/bin/bin/uic.
--- --- --- --- --- --- ---
OK   
--- --- --- --- --- --- ---

**Comment by altendky** [comment]
I get that as well:
![image](https://user-images.githubusercontent.com/543719/65258577-2416ba00-dad1-11e9-87db-5682f0fb9f45.png)

There is a command you have to run, `Scripts\pyqt5toolsinstalluic.exe`:
https://github.com/altendky/pyqt5-tools/blame/0e0d1e59e60242b2c7e776392f4047c2cf1ebf10/README.rst#L98-L102

After which I get:

![image](https://user-images.githubusercontent.com/543719/65258650-398be400-dad1-11e9-8c6c-8d8a24d39293.png)

Let me know if that works for you.

**Comment by altendky** [comment]
I'm also not exactly sure why the original fails now rather than just giving you C++, but hey...
