### ISSUE TITLE
Installing pyqt5-tools in Windows: Connection aborted issue

### ISSUE THREAD

**Issue by ktwalker** [altendky/pyqt-tools#39]
Dear Folks,

I am fairly inexperienced with Python.  Please bear with me.

Environment: Windows OS, pip 19.1.1 from anaconda installation.

I am interested in learning how to develop GUI's in PyQT.  An online video suggested the way to start was to download pyqt5-tools using pip.  The errors I get are:

(base) C:\Users\kwdh>pip install pyqt5-tools --verbose
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Created temporary directory: C:\Users\kwdh\AppData\Local\Temp\pip-ephem-wheel-cache-fmw_27a7
Created temporary directory: C:\Users\kwdh\AppData\Local\Temp\pip-req-tracker-3x_y37s_
Created requirements tracker 'C:\\Users\\kwdh\\AppData\\Local\\Temp\\pip-req-tracker-3x_y37s_'
Created temporary directory: C:\Users\kwdh\AppData\Local\Temp\pip-install-bb68fzo5
Collecting pyqt5-tools
  1 location(s) to search for versions of pyqt5-tools:
  * https://pypi.org/simple/pyqt5-tools/
  Getting page https://pypi.org/simple/pyqt5-tools/
  Looking up "https://pypi.org/simple/pyqt5-tools/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pyqt5-tools/
  Starting new HTTPS connection (2): pypi.org:443
  Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=3, connect=None, read=None, redirect=None, status=None)
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pyqt5-tools/
  Starting new HTTPS connection (3): pypi.org:443
  Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pyqt5-tools/
  Starting new HTTPS connection (4): pypi.org:443
  Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pyqt5-tools/
  Starting new HTTPS connection (5): pypi.org:443
  Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pyqt5-tools/
  Starting new HTTPS connection (6): pypi.org:443
  Could not fetch URL https://pypi.org/simple/pyqt5-tools/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pyqt5-tools/ (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))) - skipping
  ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none)
Cleaning up...
Removed build tracker 'C:\\Users\\kwdh\\AppData\\Local\\Temp\\pip-req-tracker-3x_y37s_'
ERROR: No matching distribution found for pyqt5-tools
Exception information:
Traceback (most recent call last):
  File "C:\Users\kwdh\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "C:\Users\kwdh\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "C:\Users\kwdh\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\kwdh\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\kwdh\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\kwdh\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 282, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "C:\Users\kwdh\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_internal\req\req_install.py", line 198, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\kwdh\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_internal\index.py", line 792, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pyqt5-tools
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Looking up "https://pypi.org/simple/pip/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Could not fetch URL https://pypi.org/simple/pip/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))) - skipping

I also have Windows Subsystem for Linux on the same Windows machine, with pip 19.3.1 from miniconda/python3.7.

Here is the error there:

(base) ktwalker@pf1f54yv20l6:~$ pip --verbose install pyqt5-tools
Created temporary directory: /tmp/pip-ephem-wheel-cache-xliq7ixo
Created temporary directory: /tmp/pip-req-tracker-vh1fg4hi
Created requirements tracker '/tmp/pip-req-tracker-vh1fg4hi'
Created temporary directory: /tmp/pip-install-jvynshat
1 location(s) to search for versions of pyqt5-tools:
* https://pypi.org/simple/pyqt5-tools/
Getting page https://pypi.org/simple/pyqt5-tools/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pyqt5-tools/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')"))': /simple/pyqt5-tools/
Starting new HTTPS connection (2): pypi.org:443
Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=3, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')"))': /simple/pyqt5-tools/
Starting new HTTPS connection (3): pypi.org:443
Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')"))': /simple/pyqt5-tools/
Starting new HTTPS connection (4): pypi.org:443
Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')"))': /simple/pyqt5-tools/
Starting new HTTPS connection (5): pypi.org:443
Incremented Retry for (url='/simple/pyqt5-tools/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')"))': /simple/pyqt5-tools/
Starting new HTTPS connection (6): pypi.org:443
Could not fetch URL https://pypi.org/simple/pyqt5-tools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pyqt5-tools/ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')"))) - skipping
Given no hashes to check 0 links for project 'pyqt5-tools': discarding no candidates
ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none)
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-vh1fg4hi'
ERROR: No matching distribution found for pyqt5-tools
Exception information:
Traceback (most recent call last):
  File "/home/ktwalker/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/home/ktwalker/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/home/ktwalker/miniconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/ktwalker/miniconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/ktwalker/miniconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 311, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, self.require_hashes)
  File "/home/ktwalker/miniconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 225, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/ktwalker/miniconda3/lib/python3.7/site-packages/pip/_internal/index.py", line 906, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pyqt5-tools
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pip/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')"))) - skipping
Given no hashes to check 0 links for project 'pip': discarding no candidates

Any ideas to my issue?  I do not have a proxy server.  But I am behind firewalls.  I can do apt-get installs just fine and use curl to get stuff without issue in general.  But for some reason, I have issues with pypi.org website here and with other packages.

Kind regards,
Kris

**Comment by The-Compiler** [comment]
This indeed seems like an issue with your network (or possibly pypi.org). Can you access  https://pypi.org/ in a browser? If so, what about https://pypi.org/simple/pyqt5-tools/? If both work, can you try whether pip now works as well?

**Comment by altendky** [comment]
Note that Linux (WSL) is not supported, see #21.  Since it is an issue with other packages as well, and given the retry messages, I would suggest getting some diagnostic help through general python channels.  For example, #python on Freenode IRC.

Can you try from outside the firewall? If it's at a company can you contact their support to see if they are interfering?

**Comment by ktwalker** [comment]
@The-Compiler, I can access those in a browser on the Windows side.  Also note that I can access internet for apt-get installs just fine on both WSL and Windows side.

@altendky, thanks for the tip on WSL.  Note that I am getting the same issue for both WSL and Windows side.  Both sides can use apt-get to get packages.  I an also use curl to access other websites on the WSL side.  It seems to be specific to that site.  I am behind a company firewall.  I disabled Windows Defender firewall, but that did not help.  I have Sophos Endpoint protection, so I wonder if that is somehow interfering with credential checking.  I have IT support, but so far no luck had.

Thank you,
Kris

**Comment by ktwalker** [comment]
@altendky, thanks.  Those flags do not solve the issue.  

I tried to do the manual download of the win32 and _amd64 versions, but when I try to install them on the Windows side (not WSL), I get the error "not a supported wheel on this platform".  Hard to believe that there isn't a compatible version there that works with Windows 10/Intel 64.

**Comment by altendky** [comment]
What python version?  What wheel did you download?  There are lots and various versions and different versions of pyqt5-tools support different versions of Python and...

**Comment by ktwalker** [comment]
My bad.  Python 3.7.3.  Latest versions of pyqt5-tools on that website:
pyqt5_tools-5.13.2.1.6rc1-cp38-none-win32.whl
pyqt5_tools-5.13.2.1.6rc1-cp38-none-win_amd64.
Thanks.

**Comment by altendky** [comment]
https://pypi.org/project/pyqt5-tools/5.13.2.1.6rc1/#files

Note the cp38 in your file names. That refers to CPython 3.8.  So you will want a cp37 file.  You also have to pick win32 vs win_amd64 to match your Python.

**Comment by ktwalker** [comment]
@altendky, thanks!  How do you know that I need CPython 3.7?  I have anaconda and the versioning information I get when I run python is:

(base) C:\Users\kwdh>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

Is Anaconda based on CPython?  I don't understand all the differences and when distinguishing those differences is important.  

Also, I see in that version information "win32" and "64 bit (AMD64)".  Which of these takes precedence in making a decision about which distribution I need?

Thanks again!
Kris

**Comment by altendky** [comment]
CPython is what you can get from python.org.  Anaconda doesn't develop their own Python interpreter, they package up existing ones.  Normally people use CPython but there is also PyPy which anaconda offers as well.

That is reporting that it is 64 bit so you want the win_amd64 files.

Assuming you want PyQt 5.13.2...  the most recent one that I have PyQt5 built around right now... `:[`  then you want this file.

https://files.pythonhosted.org/packages/1e/0f/6ec913fff393e9ba813cb09e13b662a18fb16c5bde8ef17679eaefea913d/pyqt5_tools-5.13.2.1.6rc1-cp37-none-win_amd64.whl

Do note that it has dependencies that pip will complain about not having and you will have to go download as well.

**Comment by altendky** [comment]
Just cleaning up.  Seems this conversation has finished.
