### ISSUE TITLE
msvcp140.dll is missing

### ISSUE THREAD

**Issue by amryounis** [altendky/pyqt-tools#46]
environment:

pycharm ce 2020
python 3.82
pyqt5 5,14

**Comment by altendky** [comment]
Thanks for the feedback.  I'll try to get that straightened out.  Do you have a full traceback to share in case it is any extra help to me?

**Comment by altendky** [comment]
Also, what were you running?  And what version of Windows?

**Comment by amryounis** [comment]
Hi, thank you for the reply.

I installed MS VC++ redist for Windows which solved the this issue (this requirement was mentioned anywhere)

after that if I try to launch designer.exe (C:\...\PycharmProjects\...\venv\Lib\site-packages\pyqt5_tools\Qt\bin) I receive an error message that "the application failed to start because no Qt plugin could be initialized"

After some search I came to know that I have to start  pyqt5designer.exe from (C:\...\PycharmProjects\...\venv\Scripts). also this was not mentioned anywhere

**Comment by altendky** [comment]
At present it is supposed to get the redist from the PyQt5 installation.  Can you link the tutorials that say to run from `Qt/bin`?  That's really old.  The readme does refer to `Scripts/pyqt5designer.exe`, but sure, it could be more explicit and refer to the other programs too.  It also needs to be updated to describe Linux (and macOS) directories which annoyingly Python makes different on different platforms.

**Comment by amryounis** [comment]
thank you...

I am referring to this tutorial: https://morioh.com/p/7fd512fef7d7
but googling the subject will lead you to similar ones as well.

I consulted project web page: https://pypi.org/project/pyqt5-tools/. The page says nothing about MSVC++ redist. also it directs me to launch Scripts\designer.exe.

I again consulted https://github.com/altendky/pyqt5-tools, with the same.

for fairness, I later found that the same two pages mentioned that I need to launch Scripts\pyqt5designer.exe, but this comes later on which meant I needed to go through the pages to the end.

**Comment by altendky** [comment]
As mentioned, you should not need to install the redist.  The previous builds included it themselves.  The new builds use the pyqt5 provided redist files.  If you launch correctly...

Yes, the readme ought to be improved.  Yes, you do have to read it instead of running random files down in site-libs.

I'll keep this open until I improve the readme or create other explicit tickets for those steps.  If you would be willing to dig up the other links to outdated tutorials I can write up a message and contact all the authors.

**Comment by amryounis** [comment]
thank you for your keen follow up. Surely I can try to update this issue with any similar encounters

**Comment by stonebig** [comment]
maybe could you use Cgohlke wheel ? 

https://www.lfd.uci.edu/~gohlke/pythonlibs/#msvc_runtime

or 

https://pypi.org/project/msvc-runtime/

**Comment by altendky** [comment]
Just cleaning up old issues here.  If there is still a similar issue on the latest releases from today, please open a new issue with details.
