### ISSUE TITLE
Incomplete wheelhouse for v1.7.5

### ISSUE THREAD

**Issue by altendky** [altendky/pyqt-tools#58]
Yep, ran into PyPI's 30GB project limit so only some of the v1.7.5 wheels (with the translations files in Linux) were successfully uploaded.  I need to find time to go through my options and resolve this.

**Comment by stonebig** [comment]
Would it be also possible to get a Python-3.9 wheel for Windows 10 64 bit ?

**Comment by altendky** [comment]
They won't get published until this is resolved but you could open another issue for 3.9 support.

**Comment by altendky** [comment]
Not having actually dug into it, I think breaking this project apart makes the most sense.  The Qt applications are not dependent on the Python version so processing them for each and storing artifacts for each is 'a waste'.  This package can then depend on that one.  I'll have to think more if there's any sense in breaking out the compiled plugins to a third package.  If I reduce my expected future consumption I would expect to just ask for an increase to the limit on PyPI to avoid removing old files.

**Comment by altendky** [comment]
v2 has been released  with a full 5.14.0+ complement.  v1.7.5 will remain incomplete.
