### ISSUE TITLE
Support 5.15.2

### ISSUE THREAD

**Issue by altendky** [altendky/pyqt-tools#73]
Held up, sort of, on the issue(s) below.  May just adjust the CI to bypass this, but I haven't yet.

https://bugreports.qt.io/browse/QTBUG-88688
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975259

**Comment by stonebig** [comment]
any hope for PyQt5-5.15.4 on pypi ? 5.15.3 is supposed to  have fix th 1st bug but for the deban one I don't know

**Comment by altendky** [comment]
@stonebig, yeah, thanks for the reminder.  I've been getting pulled around on various projects and need to get back to this family.  Looks like I did get the support added, I just need to figure out what steps to release.  Sorry for the wait.

**Comment by altendky** [comment]
Looks like 5.15.3 and 5.15.4 versions are uploaded now.  If there are any issues, please open a new ticket.

@stonebig, thanks again for the bump on this.

https://pypi.org/project/pyqt5-tools/5.15.4.3.0.3/
https://pypi.org/project/pyqt5-tools/5.15.3.3.0.3/
https://pypi.org/project/pyqt5-tools/5.15.2.3.0.3/
