### ISSUE TITLE
Command "pyqt5-tools installuic" failed because it can't find the file 'pyuic5.exe'

### ISSUE THREAD

**Issue by yehnan** [altendky/pyqt-tools#78]
My environment: Windows 10 and Python 3.7.9(virtual env named py37qt created by Miniconda).

After installed PyQt5 and pyqt5-tools using pip, the Qt Designer can be successfully launched using the command "pyqt5-tools designer".

Then I tried the command "pyqt5-tools installuic", it failed with the following error message.
It seems the command tried to copy the file 'c:\\miniconda3\\envs\\py37qt\\pyuic5.exe', however,
that file exists in 'C:\Miniconda3\envs\py37qt\Scripts'.

```python-traceback
(py37qt) R:\>pyqt5-tools installuic
Traceback (most recent call last):
  File "c:\miniconda3\envs\py37qt\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3\envs\py37qt\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\py37qt\Scripts\pyqt5-tools.exe\__main__.py", line 7, in <module>
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\miniconda3\envs\py37qt\lib\site-packages\pyqt5_tools\entrypoints.py", line 64, in installuic
    dst=str(destination/maybe_extension('uic')),
  File "c:\miniconda3\envs\py37qt\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\miniconda3\envs\py37qt\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\miniconda3\\envs\\py37qt\\pyuic5.exe'
```

**Comment by altendky** [comment]
Thanks for the report.  Seems like it shouldn't be a big deal to recreate and fix.  I'll see what I can do.

**Comment by altendky** [comment]
Hmm... Tests passed.  Could you run `print(sysconfig.get_paths())` and share the output please?  Thanks.

**Comment by yehnan** [comment]
The output of print(sysconfig.get_paths()):
{'stdlib': 'c:\\miniconda3\\envs\\py37qt\\Lib', 'platstdlib': 'c:\\miniconda3\\envs\\py37qt\\Lib', 'purelib': 'c:\\miniconda3\\envs\\py37qt\\Lib\\site-packages', 'platlib': 'c:\\miniconda3\\envs\\py37qt\\Lib\\site-packages', 'include': 'c:\\miniconda3\\envs\\py37qt\\Include', 'platinclude': 'c:\\miniconda3\\envs\\py37qt\\Include', 'scripts': 'c:\\miniconda3\\envs\\py37qt\\Scripts', 'data': 'c:\\miniconda3\\envs\\py37qt'}

**Comment by altendky** [comment]
Well, my first efforts to recreate the issue in CI failed...  but I think I know the problem anyways.  Could you please try installing the appropriate wheel from [this build](https://github.com/altendky/pyqt-tools/actions/runs/485774991) and check if it works for you?  You will have to download the artifact `.zip` then extract the `.whl` then install that file with pip.  If it does I can get an updated release out today.

**Comment by yehnan** [comment]
The .whl file you provided can be installed and the the command 'pyqt5-tools installuic' can be executed successfully.

My test procedure is:
conda create -n py37qt_test python=3.7
conda activate py37qt_test
conda install PyQt5      # it installed version PyQt5-5.15.2
conda install "pyqt5_tools-5.15.2.3.post15+g23977e3-py3-none-any.whl"
pyqt5-tools designer    # Qt Designer launched successfully
pyqt5-tools installuic    # it completed without outputting any message


Some notes:

I have two virtual environments now:
py37qt: pyqt5-tools installed from PyPI. The command 'pyqt5-tools installuic' failed.
py37qt_test: pyqt5-tools installed from the .whl file you provided. The command 'pyqt5-tools installuic' succeed.

However, both of the virtual envs has only one 'pyuic5.exe' in their 'Scripts' folder. Why does py37qt_test not copy 'pyuic5.exe' to somewhere?

The Menu->View Python Code of Qt Designer can work in both of them.

**Comment by altendky** [comment]
So this feature copies the `pyuic5` executable down into the `site-packages` directories.  At the time anyways, my understanding was that Designer looked in a hardcoded spot for the original Qt `uic` executable.  This copies the `pyuic5` from scripts down over Qt's `uic`.  These days Designer may have builtin separate support for viewing either C++ or Python generated code.  But, if it does then that would be for PySide output not PyQt output.  Double check the imports.

The feature and docs maybe need to be updated but I'll go ahead and merge and release this fix.  Thanks for testing.

**Comment by yehnan** [comment]
I compared the sha1 hash of the files 'uic.exe' and 'pyuic5.exe' in my two virtual environments.

Before command 'pyqt5-tools installuic':
There is a 'uic.exe' in Lib\site-packages\qt5_applications\Qt\bin folder, and
there is a 'pyuic5.exe' in Scripts folder.

After the command executed(only py37qt_test env):
The file 'Scripts\pyuic5.exe' got copied to 'Lib\site-packages\pyqt5_tools\Qt\bin\bin\uic.exe'.

> These days Designer may have builtin separate support for viewing either C++ or Python generated code.
As you said, Menu->View Python Code of my both Qt Designers uses 'import PySide2'.

**Comment by altendky** [comment]
@yehnan, I just got the release out this morning.

https://pypi.org/project/pyqt5-tools/5.15.2.3.0.1/

Anyways, I just got around to looking it over and it doesn't seem to actually do anything.  Designer's Python code preview shows PySide code and `installuic` isn't affecting the C++ preview either.  So, I'll open up a new issue to catch up on that front.

**Comment by altendky** [comment]
I ought have tested this more and resolved the other issues before releasing, sorry.  But, I think it's fixed over in #84.  Though you have to choose the `C++` option from Designer, not Python.

**Comment by yehnan** [comment]
Thank you.

I'm away from my computer now.
I'll test your new release on Sunday night.

**Comment by yehnan** [comment]
I created a new virtual env and installed PyQt5 and pyqt5-tools.

After the command "pyqt5-tools install", menu Form->View Python Code... of Qt Designer shows an error dialog "Usage: pyuic5 [options] <ui-file>    uic:error: no such option: -g".

The screenshot of the dialog:
https://imgur.com/a/aHJ2LpH

**Comment by altendky** [comment]
Yes, you have to use the view C++ code option.  We've got three possible options of code type to view.  Just using Designer you get C++ and PySide.  After running `installuic` you get PyQt5 via the C++ menu option.  I can probably make something that works more nicely but haven't yet.
