### ISSUE TITLE
qt5designer.exe missing

### ISSUE THREAD

**Issue by owillebo** [altendky/pyqt-tools#85]
The README metiones;

`For each tool a script is created such that you get files like Scripts/qt5designer.exe to launch the programs.`

Is this no longer the case and must 'qt5-tools.exe designer' be used to start the designer or is this a bug?

**Comment by altendky** [comment]
This was an intentional change.  My apologies for not updating the readme and thank you for raising the issue.  I'll update the readme.

**Comment by altendky** [comment]
The update has been submitted as #87 and can be viewed as below.

Rendered: https://github.com/altendky/pyqt-tools/tree/23ade47116a6beb31652ba2706ee980e2c807c23
Source diff: https://github.com/altendky/pyqt-tools/pull/87/files

Let me know if this has fixed the issues.

**Comment by altendky** [comment]
I went ahead and merged #87.  If there are any remaining issues on this particular error, please reopen this ticket.  If you find other errors, another issue would be appreciated.  Thanks for your feedback, it definitely helps keep this project a little tidier.
