### ISSUE TITLE
pyqt5-tools.exe must wait for started executables

### ISSUE THREAD

**Issue by owillebo** [altendky/pyqt-tools#86]
pyqt5-tools.exe now exits once it started 1 of the executables.

This is very inconvenient if used programmatically.

Please have pyqt5-tools.exe wait until the executable it starts, ended and have it return the executable exit code.

**Comment by altendky** [comment]
The behavior you describe is what I intended.  It was not supposed to change to returning immediately.  Thanks for pointing this out and I'll take a look at it.

**Comment by altendky** [comment]
I didn't observe this for Designer in Windows.  What are you running that exits early?  And to be sure, could you share the Python version and pyqt5-tools version?  Thanks.

**Comment by owillebo** [comment]
You are absolutely right. I somehow mixed things up. Please close this
issue. Sorry to have bothered you.

**Comment by altendky** [comment]
No problem, let me know if anything else comes up.  `:]`
