### ISSUE TITLE
Executables in windows 10

### ISSUE THREAD

**Issue by betopicapiedra** [altendky/pyqt-tools#88]
**### I can't find the executables for designer linguist and others**

**Comment by altendky** [comment]
Sorry for the trouble.  In the past year the command line interface has been changed to use a few executables with subcommands to avoid cluttering and gain the other benefits of namespacing.  The program is now `pyqt5-tools` and designer would be run such as `pyqt5-tools designer`.

https://github.com/altendky/pyqt-tools#usage

The generic tools that pyqt5-tools doesn't provide any enhancements to are available as `qt5-tools linguist`, for example.

If this doesn't address your question then I'll need some more info.  What version of pyqt5-tools do you have and where are you looking for the executables and with what name?

**Comment by betopicapiedra** [comment]
**### Before it was easy to find the Designer exe and the other programs, now I can't find them and I don't know how to open those programs (I don't speak English and I don't understand what you sent me, I'm using Windows 10**

**Comment by altendky** [comment]
```console
PS C:\Users\sda\desktop> py -3 -m venv myvenv
```
```console
PS C:\Users\sda\desktop> myvenv/scripts/pip install pyqt5-tools
Collecting pyqt5-tools
  Downloading pyqt5_tools-5.15.2.3.0.2-py3-none-any.whl (28 kB)
Collecting pyqt5-plugins<5.15.2.3,>=5.15.2.2
  Using cached pyqt5_plugins-5.15.2.2.0.1-cp39-cp39-win_amd64.whl (65 kB)
Collecting click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting pyqt5==5.15.2
  Using cached PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl (56.9 MB)
Collecting python-dotenv
  Using cached python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
Collecting qt5-tools<5.15.2.2,>=5.15.2.1
  Using cached qt5_tools-5.15.2.1.0.1-py3-none-any.whl (12 kB)
Collecting PyQt5-sip<13,>=12.8
  Using cached PyQt5_sip-12.8.1-cp39-cp39-win_amd64.whl (63 kB)
Collecting qt5-applications<5.15.2.3,>=5.15.2.2
  Using cached qt5_applications-5.15.2.2.1-py3-none-win_amd64.whl (61.0 MB)
Installing collected packages: click, PyQt5-sip, pyqt5, qt5-applications, qt5-tools, pyqt5-plugins, python-dotenv, pyqt5-tools
Successfully installed PyQt5-sip-12.8.1 click-7.1.2 pyqt5-5.15.2 pyqt5-plugins-5.15.2.2.0.1 pyqt5-tools-5.15.2.3.0.2 python-dotenv-0.15.0 qt5-applications-5.15.2.2.1 qt5-tools-5.15.2.1.0.1
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\users\sda\desktop\myvenv\scripts\python.exe -m pip install --upgrade pip' command.
```
```console
PS C:\Users\sda\desktop> myvenv/scripts/pyqt5-tools designer --help
Usage: pyqt5-tools designer [OPTIONS]

Options:
  -p, --widget-path DIRECTORY     Paths to be combined with PYQTDESIGNERPATH
  --example-widget-path           Include the path for the pyqt5-tools example
                                  button
                                  (c:\users\sda\desktop\myvenv\lib\site-
                                  packages\pyqt5_plugins)

  --designer-help                 Pass through to get Designer's --help
  --test-exception-dialog         Raise an exception to check the exception
                                  dialog functionality.

  --qt-debug-plugins / --no-qt-debug-plugins
                                  Set QT_DEBUG_PLUGINS=1
  --help                          Show this message and exit.
```
```console
PS C:\Users\sda\desktop> myvenv/scripts/qt5-tools linguist
```

**Comment by betopicapiedra** [comment]
**I don't use virtual installations**

**Comment by betopicapiedra** [comment]
**I have everything related to python installed globally**

**Comment by altendky** [comment]
Then you don't need the paths.

**Comment by betopicapiedra** [comment]
What it says in the part of how to use it refers to creating a virtual environment and not not that

**Comment by betopicapiedra** [comment]
**How can I use it without a virtual environment?**

**Comment by altendky** [comment]
If you run `pip` instead of `myvenv/scripts/pip` then also run `pyqt5-tools` instead of `myvenv/scripts/pyqt5-tools`.  The rest should be the same as the example above.

**Comment by betopicapiedra** [comment]
I already installed with pip pyqt5-tools but the executables to use them do not appear to me

**Comment by altendky** [comment]
You need to share more information.  Uninstall pyqt5-tools.  Reinstall and try to run it and then copy and paste the whole shell session here so I can see what you did and what happened.

**Comment by betopicapiedra** [comment]
### I already found how to use it, now my question is, will you update it to the latest version of PyQt6?

**Comment by altendky** [comment]
I'm glad you got it working.

I have started on Qt6 support.  I don't have a timeline.

**Comment by betopicapiedra** [comment]
Excuse me for consulting this .. Could you help me with a problem I have to move a window without a title bar with pyqt6?

**Comment by altendky** [comment]
There are generally better venues for support.  I am often in the `#python` channel on irc.freenode.net.  There is also `#pyqt` which is more focused but only has a couple active users so you may have to wait a bit.

https://webchat.freenode.net/?channel=#python

To get into `#python` you do have to have a registered account which you have authenticated to, but it really is a great resource.

https://freenode.net/kb/answer/registration

I am in both those places so I may well still end up being the one helping you.  Let me know if you can't get that working.
