### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by betopicapiedra** [altendky/pyqt-tools#90]
### _Hello, you will update to the latest version of pyqt 6_

**Comment by altendky** [comment]
I have started into Qt 6 support but haven't made it through all the layers.  I got caught up with other projects.  I do plan to get back to it but can't put a schedule on it.  My apologies for the hassle.

**Comment by betopicapiedra** [comment]
### _I look forward to it thanks my brother_

**Comment by altendky** [comment]
Just published.  If you have any problems feel free to open another issue.
